name: Build and deploy container app

on:
  push:
    branches:
      - mmaster  # Or your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Login to Azure Container Registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: 'Build and push image'
      run: |
        docker build . -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/shop-api:latest
        docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/shop-api:latest

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-store-api' # <--- CHANGE THIS
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/shop-api:latest'